name: build and releases

on:
  push:
    branches:
      - "build"
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  go-build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get the tag
        run: echo "MIAOSPEED_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - uses: actions/setup-go@v4
        with:
          go-version: '1.25'
          cache: true

      - name: fix embeded
        run: |
          mkdir ./preconfigs/embeded/miaokoCA
          echo "${{ secrets.MIAOSPEED_CRT }}" > ./preconfigs/embeded/miaokoCA/miaoko.crt
          echo "${{ secrets.MIAOSPEED_KEY }}" > ./preconfigs/embeded/miaokoCA/miaoko.key
          echo "${{ secrets.MS_BUILDTOKEN }}" > ./utils/embeded/BUILDTOKEN.key

      - name: build
        run: make releases VERSION="$MIAOSPEED_TAG"

      - name: Release to current repository
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./bin/*.tar.gz
            ./bin/*.zip
          body_path: './CHANGELOG.md'
          tag_name: ${{ env.MIAOSPEED_TAG }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: ./.github/actions/docker-publish
        with:
          version: ${{ env.MIAOSPEED_TAG }}
          username: ${{ secrets.GHCR_USERNAME || github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN || secrets.GITHUB_TOKEN }}
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ env.MIAOSPEED_TAG }}
